# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'Welder',
            },
        ),
        migrations.CreateModel(
            name='ContinuityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('process', models.CharField(max_length=30)),
                ('weld', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welds.weld')),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder')),
            ],
            options={
                'db_table': 'ContinuityLog',
            },
        ),
        migrations.CreateModel(
            name='WelderContinuity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('continuity_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='in_continuity', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder', unique=True)),
            ],
            options={
                'db_table': 'WelderContinuity',
            },
        ),
        migrations.CreateModel(
            name='Wpq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=30)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder')),
            ],
            options={
                'db_table': 'Wpq',
            },
        ),
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('welder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder')),
                ('wpq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.wpq')),
            ],
            options={
                'db_table': 'ExpiryAlert',
            },
        ),
        migrations.CreateModel(
            name='WpqProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process', models.CharField(max_length=30)),
                ('positions', models.CharField(blank=True, max_length=100, null=True)),
                ('thickness_range', models.CharField(blank=True, max_length=50, null=True)),
                ('wpq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.wpq')),
            ],
            options={
                'db_table': 'WpqProcess',
            },
        ),
        migrations.CreateModel(
            name='WpqTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('report_path', models.CharField(blank=True, max_length=512, null=True)),
                ('wpq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.wpq')),
            ],
            options={
                'db_table': 'WpqTest',
            },
        ),
        migrations.AddConstraint(
            model_name='wpq',
            constraint=models.UniqueConstraint(fields=('welder', 'code'), name='wpq_welder_code_unique'),
        ),
    ]
