# Generated by Django 6.0.1 on 2026-01-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldercontinuity',
            name='welder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder'),
        ),
    ]
