# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NdeResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
                ('defect_type', models.CharField(blank=True, max_length=50, null=True)),
                ('report_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'NdeResult',
            },
        ),
        migrations.CreateModel(
            name='NdeSamplingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('ratio', models.DecimalField(decimal_places=3, max_digits=12)),
                ('penalty_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'NdeSamplingRule',
            },
        ),
        migrations.CreateModel(
            name='PressureTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_id', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=20)),
                ('pressure', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('duration_min', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(max_length=20)),
                ('report_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'PressureTest',
            },
        ),
        migrations.CreateModel(
            name='PwhtRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_params_json', models.JSONField(default=dict)),
                ('result', models.CharField(max_length=20)),
                ('report_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'PwhtRecord',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('applies_to', models.CharField(max_length=10)),
                ('severity', models.CharField(default='error', max_length=20)),
                ('rule_json', models.JSONField()),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'ValidationRule',
            },
        ),
        migrations.CreateModel(
            name='ValidationRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('applies_to', models.CharField(max_length=10)),
                ('standard', models.CharField(max_length=30)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'ValidationRuleSet',
            },
        ),
        migrations.CreateModel(
            name='ValidationRuleSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ValidationRuleSetItem',
            },
        ),
        migrations.CreateModel(
            name='NdeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('status', models.CharField(default='requested', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'NdeRequest',
            },
        ),
    ]
