# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('quality', '0001_initial'),
        ('users', '0001_initial'),
        ('welds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nderequest',
            name='weld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welds.weld'),
        ),
        migrations.AddField(
            model_name='nderesult',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='nderesult',
            name='nde_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.nderequest'),
        ),
        migrations.AddField(
            model_name='ndesamplingrule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='pressuretest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='pwhtrecord',
            name='weld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld'),
        ),
        migrations.AddField(
            model_name='validationrulesetitem',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.validationrule'),
        ),
        migrations.AddField(
            model_name='validationrulesetitem',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.validationruleset'),
        ),
        migrations.AddConstraint(
            model_name='validationrulesetitem',
            constraint=models.UniqueConstraint(fields=('ruleset', 'rule'), name='ruleset_rule_unique'),
        ),
    ]
