# Generated by Django 6.0.1 on 2026-01-23 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditEvent',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=50)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('diff_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='NumberingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('pattern', models.CharField(max_length=200)),
                ('next_seq', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'NumberingRule',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('units', models.CharField(default='metric', max_length=20)),
                ('status', models.CharField(default='active', max_length=30)),
                ('standard_set', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProjectUser',
            },
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('version', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SchemaVersion',
            },
        ),
    ]
