# Generated by Django 6.0.1 on 2026-01-27 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="purchase_order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ProjectTeam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("fabrication_code", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=30)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
            ],
            options={
                "db_table": "ProjectTeam",
            },
        ),
        migrations.AddConstraint(
            model_name="projectteam",
            constraint=models.UniqueConstraint(
                fields=("project", "fabrication_code"),
                name="project_team_fabrication_unique",
            ),
        ),
    ]
