# Generated by Django 6.0.1 on 2026-01-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_team_and_purchase_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectTeam",
            new_name="ProjectEquipment",
        ),
        migrations.AlterModelTable(
            name="projectequipment",
            table="ProjectEquipment",
        ),
        migrations.RemoveConstraint(
            model_name="projectequipment",
            name="project_team_fabrication_unique",
        ),
        migrations.AddConstraint(
            model_name="projectequipment",
            constraint=models.UniqueConstraint(
                fields=("project", "fabrication_code"),
                name="project_equipment_fabrication_unique",
            ),
        ),
    ]
