# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
        ('wps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='draft', max_length=30)),
            ],
            options={
                'db_table': 'Traveler',
            },
        ),
        migrations.CreateModel(
            name='WeldAttributeCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(default='text', max_length=20)),
                ('enum_values', models.JSONField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'WeldAttributeCatalog',
            },
        ),
        migrations.CreateModel(
            name='WeldWpsAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'WeldWpsAssignment',
            },
        ),
        migrations.CreateModel(
            name='WorkPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(default='open', max_length=30)),
            ],
            options={
                'db_table': 'WorkPack',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(default='active', max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'Drawing',
            },
        ),
        migrations.CreateModel(
            name='Weld',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('drawing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welds.drawing')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'Weld',
            },
        ),
        migrations.CreateModel(
            name='VisualInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
            ],
            options={
                'db_table': 'VisualInspection',
            },
        ),
        migrations.CreateModel(
            name='WeldAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
            ],
            options={
                'db_table': 'WeldAttribute',
            },
        ),
        migrations.CreateModel(
            name='WeldConsumable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.fillermaterial')),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
            ],
            options={
                'db_table': 'WeldConsumable',
            },
        ),
        migrations.CreateModel(
            name='WeldMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=30)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.drawing')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'WeldMap',
            },
        ),
        migrations.CreateModel(
            name='WeldMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
                ('weld_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weldmap')),
            ],
            options={
                'db_table': 'WeldMark',
            },
        ),
        migrations.CreateModel(
            name='WeldMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heat_number', models.CharField(max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.materialbase')),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
            ],
            options={
                'db_table': 'WeldMaterial',
            },
        ),
        migrations.CreateModel(
            name='WeldWelderAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld')),
            ],
            options={
                'db_table': 'WeldWelderAssignment',
            },
        ),
    ]
