# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
        ('welds', '0001_initial'),
        ('wpq', '0001_initial'),
        ('wps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldwelderassignment',
            name='welder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpq.welder'),
        ),
        migrations.AddField(
            model_name='weldwpsassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='weldwpsassignment',
            name='weld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.weld'),
        ),
        migrations.AddField(
            model_name='weldwpsassignment',
            name='wps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.wps'),
        ),
        migrations.AddField(
            model_name='workpack',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='work_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welds.workpack'),
        ),
        migrations.AddConstraint(
            model_name='drawing',
            constraint=models.UniqueConstraint(fields=('project', 'code', 'revision'), name='drawing_project_code_rev_unique'),
        ),
        migrations.AddConstraint(
            model_name='weld',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='weld_project_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='weldmap',
            constraint=models.UniqueConstraint(fields=('project', 'drawing'), name='weldmap_project_drawing_unique'),
        ),
    ]
