# Generated by Django 6.0.1 on 2026-01-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("welds", "0002_initial"),
        ("projects", "0004_project_equipment_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.projectequipment",
            ),
        ),
    ]
