# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillerMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec', models.CharField(max_length=100)),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('group_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FillerMaterial',
            },
        ),
        migrations.CreateModel(
            name='JointType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('geometry_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'JointType',
            },
        ),
        migrations.CreateModel(
            name='MaterialBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('group_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'MaterialBase',
            },
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=30)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'db_table': 'Pqr',
            },
        ),
        migrations.CreateModel(
            name='PqrResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('report_path', models.CharField(blank=True, max_length=512, null=True)),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.pqr')),
            ],
            options={
                'db_table': 'PqrResult',
            },
        ),
        migrations.CreateModel(
            name='Wps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=30)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'db_table': 'Wps',
            },
        ),
        migrations.CreateModel(
            name='WpsPqrLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.pqr')),
                ('wps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.wps')),
            ],
            options={
                'db_table': 'WpsPqrLink',
            },
        ),
        migrations.CreateModel(
            name='WpsVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('wps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wps.wps')),
            ],
            options={
                'db_table': 'WpsVariable',
            },
        ),
        migrations.AddConstraint(
            model_name='pqr',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='pqr_project_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='wps',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='wps_project_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='wpspqrlink',
            constraint=models.UniqueConstraint(fields=('wps', 'pqr'), name='wps_pqr_unique'),
        ),
    ]
