# Generated by Django 6.0.1 on 2026-01-27 00:02

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wps",
            name="impact_test",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WpsProcess",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("process_code", models.CharField(choices=[("SMAW", "SMAW"), ("GTAW", "GTAW"), ("GMAW", "GMAW")], max_length=20)),
                ("special_process", models.CharField(blank=True, choices=[("HFO", "HFO"), ("CRO", "CRO")], max_length=10, null=True)),
                ("order", models.IntegerField(default=1)),
                ("wps", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wps.wps")),
            ],
            options={
                "db_table": "WpsProcess",
            },
        ),
        migrations.CreateModel(
            name="WpsVariableDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("process_code", models.CharField(max_length=20)),
                ("special_process", models.CharField(blank=True, max_length=10, null=True)),
                ("category", models.CharField(choices=[("essential", "Essential"), ("supplementary", "Supplementary Essential"), ("nonessential", "Nonessential")], max_length=20)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                ("data_type", models.CharField(choices=[("text", "Text"), ("number", "Number"), ("enum", "Enum"), ("boolean", "Boolean")], default="text", max_length=20)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("options_json", models.JSONField(blank=True, null=True)),
                ("change_note", models.CharField(blank=True, max_length=100, null=True)),
                ("paragraph", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "WpsVariableDefinition",
            },
        ),
        migrations.CreateModel(
            name="WpsVariableValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("definition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wps.wpsvariabledefinition")),
                ("wps_process", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wps.wpsprocess")),
            ],
            options={
                "db_table": "WpsVariableValue",
            },
        ),
        migrations.AddConstraint(
            model_name="wpsprocess",
            constraint=models.UniqueConstraint(fields=("wps", "process_code"), name="wps_process_unique"),
        ),
        migrations.AddConstraint(
            model_name="wpsvariabledefinition",
            constraint=models.UniqueConstraint(fields=("process_code", "special_process", "code"), name="wps_var_def_unique"),
        ),
        migrations.AddConstraint(
            model_name="wpsvariablevalue",
            constraint=models.UniqueConstraint(fields=("wps_process", "definition"), name="wps_var_value_unique"),
        ),
    ]
