# Generated by Django 6.0.1 on 2026-01-27 00:03

from django.db import migrations


def seed_smaw_defs(apps, schema_editor):
    WpsVariableDefinition = apps.get_model("wps", "WpsVariableDefinition")

    def upsert(defs):
        for item in defs:
            WpsVariableDefinition.objects.get_or_create(
                process_code=item["process_code"],
                special_process=item.get("special_process"),
                code=item["code"],
                defaults=item,
            )

    standard = [
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-402.1", "name": "groove_design", "label": "Groove design", "paragraph": "QW-402.1"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-402.4", "name": "backing", "label": "Backing", "paragraph": "QW-402.4"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-402.10", "name": "root_spacing", "label": "Root spacing", "paragraph": "QW-402.10"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-402.11", "name": "retainers", "label": "Retainers", "paragraph": "QW-402.11"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-403.5", "name": "group_number", "label": "Group number", "paragraph": "QW-403.5"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-403.6", "name": "t_limits", "label": "T limits", "paragraph": "QW-403.6"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-403.8", "name": "p_number_qualified", "label": "P-Number qualified", "paragraph": "QW-403.8"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-403.9", "name": "t_pass_over_half_in", "label": "T pass > 1/2 in. (13 mm)", "paragraph": "QW-403.9"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-403.11", "name": "p_no_qualified", "label": "P-No. qualified", "paragraph": "QW-403.11"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-404.4", "name": "f_number", "label": "F-Number", "paragraph": "QW-404.4"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-404.5", "name": "a_number", "label": "A-Number", "paragraph": "QW-404.5"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-404.6", "name": "diameter", "label": "Diameter", "paragraph": "QW-404.6"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-404.12", "name": "classification_supp", "label": "Classification", "paragraph": "QW-404.12"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-404.30", "name": "t", "label": "T", "paragraph": "QW-404.30"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-404.33", "name": "classification_nonessential", "label": "Classification", "paragraph": "QW-404.33"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-405.1", "name": "position", "label": "Position", "paragraph": "QW-405.1", "change_note": "+"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-405.3", "name": "t_plus_1_vertical", "label": "T+1 Vertical welding", "paragraph": "QW-405.3"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-406.1", "name": "preheat_decrease_over_100f", "label": "Decrease > 100°F (55°C)", "paragraph": "QW-406.1", "change_note": "Decrease > 100°F (55°C)"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-406.2", "name": "preheat_maintenance", "label": "Preheat maintenance", "paragraph": "QW-406.2"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-406.3", "name": "preheat_increase_over_100f_impact", "label": "Increase > 100°F (55°C) (Impact Test)", "paragraph": "QW-406.3", "change_note": "Increase > 100°F (55°C)"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-407.1", "name": "pwht", "label": "PWHT", "paragraph": "QW-407.1"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-407.2", "name": "pwht_tt_range", "label": "PWHT (T&T range)", "paragraph": "QW-407.2"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-409.1", "name": "heat_input", "label": "Heat input", "paragraph": "QW-409.1", "change_note": ">"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-409.4", "name": "current_or_polarity", "label": "Current or polarity", "paragraph": "QW-409.4"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-409.8", "name": "ie_range", "label": "I&E range", "paragraph": "QW-409.8"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-409.30", "name": "current_or_polarity_supp", "label": "Current or polarity", "paragraph": "QW-409.30"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.1", "name": "string_or_weave", "label": "String or weave", "paragraph": "QW-410.1"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.5", "name": "method_of_cleaning", "label": "Method of cleaning", "paragraph": "QW-410.5"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.6", "name": "method_back_gouge", "label": "Method back gouge", "paragraph": "QW-410.6"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.9", "name": "multiple_to_single_pass_side", "label": "Multiple to single pass/side", "paragraph": "QW-410.9"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.25", "name": "manual_or_automatic", "label": "Manual or automatic", "paragraph": "QW-410.25"},
        {"process_code": "SMAW", "special_process": None, "category": "nonessential", "code": "QW-410.26", "name": "peening", "label": "Peening", "paragraph": "QW-410.26"},
        {"process_code": "SMAW", "special_process": None, "category": "essential", "code": "QW-410.64", "name": "use_of_thermal_processes", "label": "Use of thermal processes", "paragraph": "QW-410.64"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-410.87", "name": "multiple_to_single_pass_side_supp", "label": "Multiple to single pass/side", "paragraph": "QW-410.87"},
        {"process_code": "SMAW", "special_process": None, "category": "supplementary", "code": "QW-410.92", "name": "bead_width", "label": "Bead width", "paragraph": "QW-410.92"},
    ]

    special_hfo = [
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-402.16", "name": "finished_t", "label": "Finished t", "paragraph": "QW-402.16", "change_note": "<"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-403.20", "name": "p_number", "label": "P-Number", "paragraph": "QW-403.20"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-403.23", "name": "t_qualified", "label": "T Qualified", "paragraph": "QW-403.23"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-404.12", "name": "classification", "label": "Classification", "paragraph": "QW-404.12"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "nonessential", "code": "QW-404.38", "name": "diameter_first_layer", "label": "Diameter (1st layer)", "paragraph": "QW-404.38"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-405.4", "name": "position", "label": "Position", "paragraph": "QW-405.4", "change_note": "+"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-406.4", "name": "preheat_dec_over_100f_interpass", "label": "Decrease > 100°F (55°C) preheat > interpass", "paragraph": "QW-406.4"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-407.6", "name": "pwht", "label": "PWHT", "paragraph": "QW-407.6"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-409.4", "name": "current_or_polarity", "label": "Current or polarity", "paragraph": "QW-409.4"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "nonessential", "code": "QW-409.8", "name": "ie_range", "label": "I&E range", "paragraph": "QW-409.8"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-409.22", "name": "increase_over_10pct_first_layer", "label": "Increase > 10% (1st layer)", "paragraph": "QW-409.22"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "nonessential", "code": "QW-410.1", "name": "string_or_weave", "label": "String or weave", "paragraph": "QW-410.1"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "nonessential", "code": "QW-410.5", "name": "method_of_cleaning", "label": "Method of cleaning", "paragraph": "QW-410.5"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "nonessential", "code": "QW-410.26", "name": "peening", "label": "Peening", "paragraph": "QW-410.26"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-410.38", "name": "multiple_to_single_layer", "label": "Multiple to single layer", "paragraph": "QW-410.38"},
        {"process_code": "SMAW", "special_process": "HFO", "category": "essential", "code": "QW-410.92", "name": "bead_width", "label": "Bead width", "paragraph": "QW-410.92"},
    ]

    special_cro = [
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-402.16", "name": "finished_t", "label": "Finished t", "paragraph": "QW-402.16", "change_note": "<"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-403.20", "name": "p_number", "label": "P-Number", "paragraph": "QW-403.20"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-403.23", "name": "t_qualified", "label": "T Qualified", "paragraph": "QW-403.23"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-404.12", "name": "classification", "label": "Classification", "paragraph": "QW-404.12"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-404.37", "name": "a_number", "label": "A-Number", "paragraph": "QW-404.37"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "nonessential", "code": "QW-404.38", "name": "diameter_first_layer", "label": "Diameter (1st layer)", "paragraph": "QW-404.38"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-405.4", "name": "position", "label": "Position", "paragraph": "QW-405.4", "change_note": "+"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-406.4", "name": "preheat_dec_over_100f_interpass", "label": "Decrease > 100°F (55°C) preheat > interpass", "paragraph": "QW-406.4"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-407.9", "name": "pwht", "label": "PWHT", "paragraph": "QW-407.9"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-409.4", "name": "current_or_polarity", "label": "Current or polarity", "paragraph": "QW-409.4"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "nonessential", "code": "QW-409.8", "name": "ie_range", "label": "I&E range", "paragraph": "QW-409.8"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-409.22", "name": "increase_over_10pct_first_layer", "label": "Increase > 10% (1st layer)", "paragraph": "QW-409.22"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "nonessential", "code": "QW-410.1", "name": "string_or_weave", "label": "String or weave", "paragraph": "QW-410.1"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "nonessential", "code": "QW-410.5", "name": "method_of_cleaning", "label": "Method of cleaning", "paragraph": "QW-410.5"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "nonessential", "code": "QW-410.26", "name": "peening", "label": "Peening", "paragraph": "QW-410.26"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-410.38", "name": "multiple_to_single_layer", "label": "Multiple to single layer", "paragraph": "QW-410.38"},
        {"process_code": "SMAW", "special_process": "CRO", "category": "essential", "code": "QW-410.92", "name": "weave_width", "label": "Weave width", "paragraph": "QW-410.92"},
    ]

    upsert(standard)
    upsert(special_hfo)
    upsert(special_cro)


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0002_wps_process_and_defs"),
    ]

    operations = [
        migrations.RunPython(seed_smaw_defs, migrations.RunPython.noop),
    ]
