# Generated by Django 6.0.1 on 2026-01-27 00:05

from django.db import migrations


def replace_gtaw_defs(apps, schema_editor):
    WpsVariableDefinition = apps.get_model("wps", "WpsVariableDefinition")
    WpsVariableDefinition.objects.filter(process_code="GTAW").delete()

    defs = [
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-402.1", "name": "groove_design", "label": "Groove design", "paragraph": "QW-402.1"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-402.5", "name": "backing", "label": "Backing", "paragraph": "QW-402.5"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-402.10", "name": "root_spacing", "label": "Root spacing", "paragraph": "QW-402.10"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-402.11", "name": "retainers", "label": "Retainers", "paragraph": "QW-402.11"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-403.5", "name": "group_number", "label": "Group number", "paragraph": "QW-403.5"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-403.6", "name": "t_limits", "label": "T limits", "paragraph": "QW-403.6"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-403.8", "name": "t_qualified", "label": "T qualified", "paragraph": "QW-403.8"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-403.11", "name": "p_no_qualified", "label": "P-No. qualified", "paragraph": "QW-403.11"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-404.3", "name": "size", "label": "Size", "paragraph": "QW-404.3"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-404.4", "name": "f_number", "label": "F-Number", "paragraph": "QW-404.4"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-404.5", "name": "a_number", "label": "A-Number", "paragraph": "QW-404.5"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-404.12", "name": "classification", "label": "Classification", "paragraph": "QW-404.12"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-404.14", "name": "filler", "label": "Filler", "paragraph": "QW-404.14"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-404.22", "name": "consumable_insert", "label": "Consumable insert", "paragraph": "QW-404.22"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-404.23", "name": "filler_metal_product_form", "label": "Filler metal product form", "paragraph": "QW-404.23"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-404.30", "name": "c", "label": "C", "paragraph": "QW-404.30"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-404.33", "name": "classification_nonessential", "label": "Classification", "paragraph": "QW-404.33"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-404.50", "name": "flux", "label": "Flux", "paragraph": "QW-404.50"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-405.1", "name": "position", "label": "Position", "paragraph": "QW-405.1"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-405.3", "name": "t_vertical_welding", "label": "T vertical welding", "paragraph": "QW-405.3"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-406.1", "name": "preheat_decrease_over_100f", "label": "Decrease > 100°F (55°C)", "paragraph": "QW-406.1"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-406.3", "name": "preheat_increase_over_100f_ip", "label": "Increase > 100°F (55°C) (IP)", "paragraph": "QW-406.3"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-407.1", "name": "pwht", "label": "PWHT", "paragraph": "QW-407.1"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-407.2", "name": "pwht_tt_range", "label": "PWHT (T&T range)", "paragraph": "QW-407.2"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-408.1", "name": "trail_or_comp", "label": "Trail or composition", "paragraph": "QW-408.1"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-408.2", "name": "single_mixture_percent", "label": "Single, mixture, or %", "paragraph": "QW-408.2"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-408.3", "name": "flow_rate", "label": "Flow rate", "paragraph": "QW-408.3"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-408.5", "name": "backing_flow", "label": "Backing flow", "paragraph": "QW-408.5"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-408.9", "name": "backing_or_comp", "label": "Backing or composition", "paragraph": "QW-408.9"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-408.10", "name": "trail_or_comp_2", "label": "Trail or composition", "paragraph": "QW-408.10"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-409.1", "name": "heat_input", "label": "Heat input", "paragraph": "QW-409.1"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-409.3", "name": "pulsing_i", "label": "Pulsing I", "paragraph": "QW-409.3"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-409.4", "name": "current_or_polarity", "label": "Current or polarity", "paragraph": "QW-409.4"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-409.8", "name": "ie_range", "label": "I&E range", "paragraph": "QW-409.8"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-409.12", "name": "tungsten_electrode", "label": "Tungsten electrode", "paragraph": "QW-409.12"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-409.30", "name": "current_or_polarity_supp", "label": "Current or polarity", "paragraph": "QW-409.30"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.1", "name": "string_or_weave", "label": "String or weave", "paragraph": "QW-410.1"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.3", "name": "orifice_cup_nozzle_size", "label": "Orifice, cup, or nozzle size", "paragraph": "QW-410.3"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.5", "name": "method_cleaning", "label": "Method cleaning", "paragraph": "QW-410.5"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.6", "name": "method_back_gouge", "label": "Method back gouge", "paragraph": "QW-410.6"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.7", "name": "oscillation", "label": "Oscillation", "paragraph": "QW-410.7"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.9", "name": "multi_to_single_pass_side", "label": "Multi to single pass per side", "paragraph": "QW-410.9"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-410.10", "name": "single_to_multi_electrodes", "label": "Single to multi electrodes", "paragraph": "QW-410.10"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-410.11", "name": "closed_to_cut_chamber", "label": "Closed to cut chamber", "paragraph": "QW-410.11"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.15", "name": "electrode_spacing", "label": "Electrode spacing", "paragraph": "QW-410.15"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.25", "name": "manual_or_automatic", "label": "Manual or automatic", "paragraph": "QW-410.25"},
        {"process_code": "GTAW", "special_process": None, "category": "nonessential", "code": "QW-410.26", "name": "peening", "label": "Peening", "paragraph": "QW-410.26"},
        {"process_code": "GTAW", "special_process": None, "category": "essential", "code": "QW-410.64", "name": "use_of_thermal_processes", "label": "Use of thermal processes", "paragraph": "QW-410.64"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-410.87", "name": "multiple_to_single_pass_side_supp", "label": "Multiple to single pass/side", "paragraph": "QW-410.87"},
        {"process_code": "GTAW", "special_process": None, "category": "supplementary", "code": "QW-410.92", "name": "bead_width", "label": "Bead width", "paragraph": "QW-410.92"},
    ]

    for item in defs:
        WpsVariableDefinition.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0004_seed_gtaw_variables"),
    ]

    operations = [
        migrations.RunPython(replace_gtaw_defs, migrations.RunPython.noop),
    ]
