# Generated by Django 6.0.1 on 2026-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wps", "0005_update_gtaw_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="pqr",
            name="scanned_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pqr_scans/"),
        ),
    ]
