# Generated by Django 6.0.1 on 2026-01-23 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DocumentApproval',
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DocumentRevision',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_blob', models.BinaryField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DocumentSignature',
            },
        ),
    ]
