# Generated by Django 6.0.1 on 2026-01-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='document_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='document_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentrevision'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
